services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mysql
    command: npm run dev

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devpulse
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
