services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: devpulse
      DB_USE_CONTAINER: "true"
      CLIENT_URL: http://localhost:3000
    command: npm run dev

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devpulse
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
